{{- if .Values.infra.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: dns-creds
type: Opaque
stringData:
    GODADDY_API_KEY: {{ .Values.apiKey }}
    GODADDY_SECRET_KEY: {{ .Values.secretKey }}
{{- end }}
